apiVersion: v1
kind: Pod
metadata:
  name: nginx-default
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-default
spec:
  containers:
    - name: centos-default
      image: centos
      ports:
        - containerPort: 80