apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: v1
kind: Pod
metadata:
  name: centos
  namespace: demo
spec:
  containers:
    - name: centos
      image: centos
      command: ["sleep"]
      args: ["10m"]
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: demo
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80